FROM node:22-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:22-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
# Cache buster — forces rebuild when GIT_SHA changes
ARG GIT_SHA=unknown
RUN echo "Building commit $GIT_SHA"
COPY . .

ARG NEXT_PUBLIC_API_BASE_URL=/api
ARG NEXT_PUBLIC_SITE_URL=https://mysanad.shop
ARG NEXT_PUBLIC_ENABLE_PIXELS=true
ARG NEXT_PUBLIC_ENABLE_ADMIN_EVENTS=true
ARG NEXT_PUBLIC_ENABLE_DEBUG_ANALYTICS=false
ARG NEXT_PUBLIC_SNAP_PIXEL_ID=b2c14550-2acd-4339-a864-2a764ab9b418
ARG NEXT_PUBLIC_META_PIXEL_ID=860397819486779
ARG NEXT_PUBLIC_TIKTOK_PIXEL_ID=D8M0REBC77UCVEHVMJQG
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_ENABLE_PIXELS=$NEXT_PUBLIC_ENABLE_PIXELS
ENV NEXT_PUBLIC_ENABLE_ADMIN_EVENTS=$NEXT_PUBLIC_ENABLE_ADMIN_EVENTS
ENV NEXT_PUBLIC_ENABLE_DEBUG_ANALYTICS=$NEXT_PUBLIC_ENABLE_DEBUG_ANALYTICS
ENV NEXT_PUBLIC_SNAP_PIXEL_ID=$NEXT_PUBLIC_SNAP_PIXEL_ID
ENV NEXT_PUBLIC_META_PIXEL_ID=$NEXT_PUBLIC_META_PIXEL_ID
ENV NEXT_PUBLIC_TIKTOK_PIXEL_ID=$NEXT_PUBLIC_TIKTOK_PIXEL_ID

RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ARG BACKEND_API_URL=https://api.mysanad.shop
ENV BACKEND_API_URL=$BACKEND_API_URL
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
CMD ["node", "server.js"]
